site_name: TOC-Demo
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
nav:
  - Player: player.md